### ISSUE TITLE
Build fails with Java 8

### ISSUE THREAD

**Issue by doe300** [jnode/jnode#41]
Hi there, I wanted to test this project and the initial build fails with following message:

    [xxx@yyy jnode]$ ./build.sh cd-x86-lite
    Buildfile: ./all/build.xml
         [echo] Setting memoryMaximumSize to 1512m
    
    prepare:
    
    BUILD FAILED
    /home/xxx/workspace/jnode/all/build.xml:222: Java Runtime version 1.6 or 1.7 needed. Your version is: 1.8.0_51-b16
    
    Total time: 0 seconds

With the following java-version:

    [xxx@yyy jnode]$ java -version
    openjdk version "1.8.0_51"
    OpenJDK Runtime Environment (build 1.8.0_51-b16)
    OpenJDK 64-Bit Server VM (build 25.51-b03, mixed mode)

On `Fedora 22` with `uname -a`:

    Linux xxx 4.1.4-100.fc21.x86_64 #1 SMP Tue Aug 4 03:25:05 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by crawley** [comment]
This is not a legitimate issue.  JNode requires Java 6 or Java 7.  If you want to build it, install the Java 7 tool-chain.

**Comment by doe300** [comment]
So I assume, the JNode kernel does not (yet) support Java 8? In which case compilation under Java 8 would not run later on and therefore forbidding it is smart.

**Comment by emarkus** [comment]
I didn't know it supports java 7?

Am 22.08.2015 um 10:00 schrieb doe300:

**Comment by dagdd** [comment]
I think the issue is quite legitimate. In fact java 7 is not longer available at Oracles website so on Windows platform you my be out of luck unless you alradey have Java 7 installed. On Mac OS platform Java 6 i still available. When the next version of Mac OS arrive next year Java 6 will no longer be available.

However, I managed to cheat the building system and build the Jnode using Java 8. Screen shot using this build is attached.
<img width="884" alt="skjermbilde 2015-12-21 kl 10 56 10" src="https://cloud.githubusercontent.com/assets/16381848/11928368/5608ba34-a7d3-11e5-8ba0-1b08c5c653f7.png">

**Comment by LSantha** [comment]
I've enabled Java 8 in the JNode build system.

**Comment by emarkus** [comment]
Levente Santha, could you please tell me your email address or write me
an email? my email-address is: markus (a-t) eserver.homelinux.org

Am 22.12.2015 um 17:37 schrieb Levente Santha:

**Comment by dagdd** [comment]
Thank you LSantha for taking care of this issue.
With regards
dagdd
