### ISSUE TITLE
Setting screen resolution results in black screen

### ISSUE THREAD

**Issue by dagdd** [jnode/jnode#50]
In the AWT gui I try to set the screen resolution (to the only option offered). This results in a black screen.
No exception is thrown.
See attached screenshots.
<img width="1176" alt="skjermbilde 2016-01-16 kl 21 40 51" src="https://cloud.githubusercontent.com/assets/16381848/12374417/1d757572-bc9b-11e5-95c3-32e18da769b4.png">
<img width="1176" alt="skjermbilde 2016-01-16 kl 21 41 23" src="https://cloud.githubusercontent.com/assets/16381848/12374422/3320b45e-bc9b-11e5-84b0-76039df2ed40.png">
<img width="1176" alt="skjermbilde 2016-01-16 kl 21 43 59" src="https://cloud.githubusercontent.com/assets/16381848/12374424/3de4e2d4-bc9b-11e5-94b6-f5880af62891.png">

**Comment by fduminy** [comment]
I know you are using the vesa mode because of the beautiful gradient from black to blue used as background :-) I wrote that part and I also tried to write a vesa driver, without concrete success (I lack knowledge of x86 protected mode and don't understand well vesa/vbe specifications).

in your case, it should probably simply do nothing or the menu item should be disabled.

**Comment by dagdd** [comment]
On my VirtualBox the Vesa mode is the mode which is working best. So you can count the Vesa driver as almost a success. So I agree with you, the screen resolution should do nothing or be disabled when running in Vesa mode.

**Comment by fduminy** [comment]
I didn't give enough details : the vesa mode you selected in the startup menu is set by grub (the bootloader of JNode) : it works fine (it's not part of JNode ;-).
The vesa driver (part of JNode) will change the screen resolution when you select the menu item. Since it's not completely implemented, that's probably why you see a black background.

**Comment by dagdd** [comment]
Thank you for the clarification.

**Comment by dagdd** [comment]
Tested the latest fix.
When I set the resolution I got the following screen (improvement as the time is now visible):
<img width="1176" alt="skjermbilde 2016-01-23 kl 19 11 45" src="https://cloud.githubusercontent.com/assets/16381848/12532270/4065258a-c210-11e5-862b-2124e162a454.png">

**Comment by LSantha** [comment]
I've tested it again and again under various conditions (virtuabox, kvm) but the black screen never occurs to me.

**Comment by dagdd** [comment]
When I tested it again with the latest build of JNode, I got no black screen. Thats great. So this issue can safely be closed.
